apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 50-var-log
spec:
  config:
    ignition:
      version: 2.2.0
    storage:
      disks:
      - device: /dev/vda
        partitions:
        - label: var-log
          number: 0
          size: 2097152
      filesystems:
      - mount:
          device: /dev/disk/by-partlabel/var-log
          format: xfs
          label: var-log
          wipeFilesystem: true
        name: var-log
    systemd:
      units:
      - contents: '[Unit]

          Before=local-fs.target

          [Mount]

          Where=/var/log

          What=/dev/disk/by-partlabel/var-log

          [Install]

          WantedBy=local-fs.target

          '
        enabled: true
        name: var-log.mount

