apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 50-walters-kargs
spec:
  config:
    ignition:
      version: 2.2.0
  kernelArguments:
    - hello=world
    - foo=bar
