[package]
name = "failpoint-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
fail = { version = "0.5", features = ["failpoints"] }

