FROM quay.io/cgwalters/centos-bootc-base-dev:stream9
COPY etc etc
COPY usr usr
# For dracut
RUN set -x; \
    kver=$(cd /usr/lib/modules && ls); \
# dnf -y update ostree bootc && \
# dnf clean all && rm -vrf /var/{lib,log,cache}/dnf && \
    dracut -v --no-hostonly -f /usr/lib/modules/$kver/initramfs.img "${kver}"
