name: Full tests

permissions:
  actions: read

on:
  pull_request:
    types: [labeled]
  workflow_dispatch:

jobs:
  fulltest:
    if: ${{ github.event.label.name == 'test-full' && github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    name: Full tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run full tests
        run: ls -al
