name: Full tests

permissions:
  actions: read

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  fulltest:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'test-full') }}
    name: Full tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run full tests
        run: ls -al
